#!/usr/bin/env python3
# Generates stable build-time secrets. Run via: go generate ./cmd/
# Re-run only when you want fresh secrets for a new deployment.
import uuid
import secrets
import os

# go generate sets cwd to the package dir (cmd/), so .. is the backend root.
root = os.path.join(os.path.dirname(__file__))

files = {
    os.path.join(root, "internal/setup/install_id.go"): (
        "setup",
        f'var installID = "{uuid.uuid4()}"',
    ),
    os.path.join(root, "internal/auth/secret.go"): (
        "auth",
        f'var secret = []byte("{secrets.token_hex(32)}")',
    ),
    os.path.join(root, "internal/utils/salt.go"): (
        "utils",
        f'var FingerprintSalt = "{secrets.token_hex(16)}"',
    ),
}

for path, (pkg, var_line) in files.items():
    with open(path, "w") as f:
        f.write(f"// Code generated by gen_secrets.py; DO NOT EDIT.\n\npackage {pkg}\n\n{var_line}\n")
    print(f"wrote {path}")
